# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420401f98105d45089879dc462a38a9625ac46fa4c6dcaf70d25ff423bd6ae7167eadccd746b0f51c3a237bbbb42e65489631bc6fd36efc75ca4587991c88acc

test:
  secret_key_base: df763f7ae253b4de22f10d805ff5a092cbb11addd584d927301a7b8a3d476c1921a38374c52db7aa5c79fd7ca93747a2db4620806287c48c6caf9ec133d20565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
